<% db_socket = ENV['DEV_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: share_tracker
  password: ZYKLjAQrZkvJhCbdfGbJahq6
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  username: root
  database: share_tracker_development
  socket: <%= db_socket %>
  password:

test:
  <<: *default
  username: root
  database: share_tracker_test
  socket: <%= db_socket %>
  password:

production:
  <<: *default
  database: share_tracker_production

